FROM python:3.11-slim

WORKDIR /app
COPY leader.py .

RUN pip install --no-cache-dir fastapi uvicorn httpx pydantic

ENV FOLLOWERS=""
ENV WRITE_QUORUM=1
ENV MIN_DELAY=0
ENV MAX_DELAY=1000

CMD ["uvicorn", "leader:app", "--host", "0.0.0.0", "--port", "8000"]
